### ISSUE TITLE
导出的coco格式的json文件的图片数和文件夹的图片数相比少了几十个

### ISSUE THREAD

**Issue by liang532** [TalkUHulk/yolov4-TT100k#1]
我运行您的转coco格式的脚本，转换后的json文件里训练集和测试集分别有6034和3016张图片的标签，而总的图片数是6105和3071张。就少了几十个图片的标签。不知道哪里出现问题了。您在转完格式后和我的结果一样吗？期待您的答复，谢谢。

**Comment by TalkUHulk** [comment]
> 我运行您的转coco格式的脚本，转换后的json文件里训练集和测试集分别有6034和3016张图片的标签，而总的图片数是6105和3071张。就少了几十个图片的标签。不知道哪里出现问题了。您在转完格式后和我的结果一样吗？期待您的答复，谢谢。

转换后的coco格式的数据分别为6103 3067，跟原始annotations.json一样。

**Comment by TalkUHulk** [comment]
> 我运行您的转coco格式的脚本，转换后的json文件里训练集和测试集分别有6034和3016张图片的标签，而总的图片数是6105和3071张。就少了几十个图片的标签。不知道哪里出现问题了。您在转完格式后和我的结果一样吗？期待您的答复，谢谢。

https://github.com/TalkUHulk/yolov3-TT100k/tree/main/scripts

**Comment by liang532** [comment]
非常感谢，这么快就回复了，我再运行下看

**Comment by liang532** [comment]
之前使用官网首页的annotations2021运行的，现在换成以前发布的注释和您运行得到的json文件一致了，和训练集测试集图片数分别就差2张和4张，可能那6张图片没有交通标志没有标注吧。非常感谢您的答复。
